language: node_js
node_js:
- '10'
cache: npm
script: npm run travis
deploy:
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep-history: true
    target-branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: build/*
    skip_cleanup: true
    on:
      tags: false
